"""Data stack: RDS Postgres + Secrets Manager credentials.

A single-AZ db.t4g.micro instance in the network stack's private
subnets, tied to its `rds_sg` security group (only the frontend tasks
can reach 5432). The master password is auto-generated by CDK and
stored in Secrets Manager — no plaintext password is ever written to
code, env files, or CloudFormation parameters. The frontend ECS task
role gets read access to the secret at startup; from there it builds
its DATABASE_URL and applies the chainlit_schema.sql idempotently
before launching Chainlit.

Dev-only choices (loud here so we remember to revisit before prod):
  - removal_policy=DESTROY, delete_automated_backups, no deletion
    protection — `cdk destroy` and `teardown_dev_stack.sh` actually
    delete the database without manual intervention.
  - Single AZ, no Multi-AZ failover.
  - 7-day backup retention is the default; not strictly needed for dev,
    but it's free and lets us recover from "oops" mid-demo.
"""

import aws_cdk as cdk
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

# Database / user names. The auto-generated password is stored alongside
# these in the Secrets Manager secret as a JSON object; nothing here is
# secret on its own.
DATABASE_NAME = "chainlit"
MASTER_USERNAME = "chainlit"
POSTGRES_PORT = 5432


class DataStack(cdk.Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        vpc: ec2.IVpc,
        rds_security_group: ec2.ISecurityGroup,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # --- Subnet group -------------------------------------------------
        # RDS hard-requires a subnet group spanning at least 2 AZs even when
        # we run a single-AZ instance, so we just hand it the network
        # stack's private subnets and let RDS pick one.
        subnet_group = rds.SubnetGroup(
            self,
            "DbSubnetGroup",
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_WITH_EGRESS),
            description="Private subnets for the Chainlit Postgres",
            removal_policy=cdk.RemovalPolicy.DESTROY,
        )

        # --- Secret + instance --------------------------------------------
        # `Credentials.from_generated_secret` creates a Secrets Manager
        # entry whose payload is { username, password, host, port,
        # dbname, engine, dbInstanceIdentifier }. The frontend reads this
        # one secret to build its DATABASE_URL.
        self.db_credentials = rds.Credentials.from_generated_secret(
            username=MASTER_USERNAME,
            secret_name="GlueAgent/Dev/ChainlitDbCredentials",
        )

        self.db_instance = rds.DatabaseInstance(
            self,
            "ChainlitDb",
            engine=rds.DatabaseInstanceEngine.postgres(
                # 16.4 was retired by AWS RDS; pick a current major.
                # Chainlit's data layer is engine-agnostic at this level
                # so the version mismatch with our local postgres:16
                # container doesn't matter for the schema or the queries.
                version=rds.PostgresEngineVersion.VER_17_5,
            ),
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.T4G,
                ec2.InstanceSize.MICRO,
            ),
            vpc=vpc,
            subnet_group=subnet_group,
            security_groups=[rds_security_group],
            credentials=self.db_credentials,
            database_name=DATABASE_NAME,
            port=POSTGRES_PORT,
            allocated_storage=20,
            max_allocated_storage=100,
            storage_type=rds.StorageType.GP3,
            multi_az=False,
            publicly_accessible=False,
            auto_minor_version_upgrade=True,
            backup_retention=cdk.Duration.days(7),
            delete_automated_backups=True,
            deletion_protection=False,
            removal_policy=cdk.RemovalPolicy.DESTROY,
            enable_performance_insights=False,
            cloudwatch_logs_exports=["postgresql"],
        )

        # The constructed DatabaseInstance.secret is exactly the SM
        # entry above; surfacing it as a typed attribute so the compute
        # stack can grant_read on it without reaching into RDS internals.
        assert self.db_instance.secret is not None
        self.db_secret: secretsmanager.ISecret = self.db_instance.secret

        # --- Outputs ------------------------------------------------------
        cdk.CfnOutput(
            self,
            "DbEndpoint",
            value=self.db_instance.db_instance_endpoint_address,
            description="Postgres host (private; reachable from inside the VPC only)",
        )
        cdk.CfnOutput(
            self,
            "DbPort",
            value=str(self.db_instance.db_instance_endpoint_port),
        )
        cdk.CfnOutput(
            self,
            "DbSecretArn",
            value=self.db_secret.secret_arn,
            description="Secrets Manager ARN holding the auto-generated DB credentials",
        )
